Repository andela/ah-frontend-thor, pull requests merged in 2018-12, with the labels that each got.

#15 #162440001 Fix folder structure
  src/Components/App.jsx
  tests/App.test.jsx
  tests/AppRouter.test.jsx
  webpack.config.js
Labels: Ready for review

#24 #162207134 setup heroku deployment
  package.json
  src/index.html
  static.json
  yarn.lock
Labels: Ready for review

#23 #161382352 Users should be able to Login to Authors Haven
  .editorconfig
  .gitignore
  README.md
  package.json
  src/actions/appAction.js
  src/actions/loginActions.js
  src/actions/types.js
  src/assets/css/styles.css
  src/components/AppRouter.jsx
  src/components/Contents.jsx
  src/components/Home.jsx
  src/components/Root.jsx
  src/components/login/Buttons.jsx
  src/components/login/Form.jsx
  src/components/login/Input.jsx
  src/components/login/SocialAuthButtons.jsx
  src/components/login/loginHelpers.jsx
  src/components/signup/SignUp.jsx
  src/components/signup/SignUpHolder.jsx
  src/containers/Login.jsx
  src/containers/container.js
  src/index.html
  src/reducers/appReducer.js
  src/reducers/loginReducer.js
  src/reducers/rootReducer.js
  src/store.js
  src/style.scss
  tests/App.test.jsx
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/endToEndTests/Sample.test.jsx
  tests/integerationTests/Content.test.jsx
  tests/integerationTests/SignUp.test.js
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Content.test.jsx.snap
  tests/integerationTests/__snapshots__/Home.test.jsx.snap
  tests/loginActions.test.jsx
  tests/loginReducers.test.jsx
  tests/loginTests.test.jsx
  tests/setupTests.js
  tests/unitTests/SignUpAction.test.js
  tests/unitTests/SignUpHolder.test.js
  yarn.lock
Labels: Ready for review

#16 #161382355 Users should be able to view and edit their profiles
  src/actions/loginActions.js
  src/actions/profileAction.js
  src/actions/signUpAction.js
  src/actions/types.js
  src/assets/css/style.css
  src/components/AppRouter.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/containers/Profile/EditProfile.jsx
  src/containers/Profile/Loading_icon.gif
  src/containers/Profile/Profile.jsx
  src/index.jsx
  src/reducers/profileReducer.jsx
  src/reducers/rootReducer.js
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/__snapshots__/profile.test.jsx.snap
  tests/integerationTests/AppRouter.test.jsx
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Footer.test.jsx.snap
  tests/integerationTests/__snapshots__/Header.test.jsx.snap
  tests/mockStore.js
  tests/profile.test.jsx
  tests/redux-mock-store.js
  webpack.config.js
  yarn.lock
Labels: Ready for review

#21 #161382353 Users should be able to Login via Google Facebook or Twitter
  .eslintrc.json
  .gitignore
  config.js
  package.json
  src/actions/socialLoginAction.js
  src/actions/types.js
  src/assets/css/styles.css
  src/components/Contents.jsx
  src/components/Footer.jsx
  src/components/Home.jsx
  src/components/Root.jsx
  src/components/login/Buttons.jsx
  src/components/login/Facebook.jsx
  src/components/login/Form.jsx
  src/components/login/Google.jsx
  src/components/login/SocialButtons.jsx
  src/index.html
  src/index.jsx
  src/reducers/rootReducer.js
  src/reducers/socialReducer.js
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/integerationTests/AppRouter.test.jsx
  tests/integerationTests/Facebook.test.jsx
  tests/integerationTests/Google.test.jsx
  tests/integerationTests/Home.test.jsx
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Google.test.jsx.snap
  tests/integerationTests/__snapshots__/Header.test.jsx.snap
  tests/integerationTests/__snapshots__/Home.test.jsx.snap
  tests/integerationTests/__snapshots__/Root.test.jsx.snap
  tests/loginTests.test.jsx
  tests/unitTests/Simple.test.jsx
  tests/unitTests/SocialReducer.test.jsx
  tests/unitTests/socialLoginAction.test.jsx
  webpack.config.js
  yarn.lock
Labels: Ready for review

#26 #162581213: Add descriptive colors to error messages
  src/actions/resetPasswordAction.jsx
  tests/unitTests/ResetActions.test.jsx
Labels: Ready for review

#30 #162652603 Users should be able to sign out
  src/assets/css/styles.css
  src/components/AppRouter.jsx
  src/components/Header.jsx
  src/components/ProfileImage.jsx
  src/components/SignOut.jsx
  src/index.html
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Footer.test.jsx.snap
  tests/profile.test.jsx
  tests/unitTests/ProfileImage.test.js
  tests/unitTests/SignOut.test.jsx
Labels: Ready for review

#31 #161382356 Users should be able to create articles
  package.json
  src/actions/articleActions.js
  src/actions/types.js
  src/assets/css/styles.css
  src/components/AppRouter.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/article/PostArticle.jsx
  src/index.html
  src/reducers/articleReducer.js
  src/reducers/rootReducer.js
  src/reducers/socialReducer.js
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/integerationTests/PostArticle.test.jsx
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Footer.test.jsx.snap
  tests/integerationTests/__snapshots__/Header.test.jsx.snap
  tests/integerationTests/__snapshots__/PostArticle.test.jsx.snap
  tests/unitTests/ArticleAction.test.jsx
  tests/unitTests/ArticleReducer.test.jsx
  yarn.lock
Labels: Ready for review

#32 #162601645: User should receive an verification link after registration
  package.json
  src/actions/types.js
  src/actions/userVerification.js
  src/components/AppRouter.jsx
  src/containers/EmailVerification.jsx
  src/index.html
  src/reducers/emailVerification.js
  src/reducers/rootReducer.js
  tests/integerationTests/EmailVerification.test.jsx
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/EmailVerification.test.jsx.snap
  tests/unitTests/EmailVerificationReducer.test.js
Labels: Ready for review

#29 #161382366 Add Search Functionality and Custom filtering based on parameters
  src/actions/getSearchDataAction.js
  src/actions/types.js
  src/assets/css/styles.css
  src/assets/scss/style.scss
  src/components/AppRouter.jsx
  src/components/Header.jsx
  src/containers/search/SearchForm.jsx
  src/containers/search/SearchResults.jsx
  src/index.html
  src/reducers/rootReducer.js
  src/reducers/searchReducer.js
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Footer.test.jsx.snap
  tests/unitTests/SearchResults.test.jsx
Labels: Ready for review

#36 ft #161382407 Add read time to a single article
  src/assets/scss/style.scss
  src/containers/viewArticles/articleView.jsx
Labels: Ready For Merge, Ready for review

#34 #161382369: List Bookmarked articles
  src/actions/bookmarksAction.js
  src/actions/types.js
  src/assets/css/styles.css
  src/assets/scss/style.scss
  src/components/AppRouter.jsx
  src/components/Header.jsx
  src/components/ProfileImage.jsx
  src/containers/bookmarks/Bookmarks.jsx
  src/index.html
  src/index.jsx
  src/reducers/bookmarksReducer.js
  src/reducers/rootReducer.js
  tests/__snapshots__/loginTests.test.jsx.snap
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/Footer.test.jsx.snap
  tests/integerationTests/__snapshots__/bookmarksContainer.test.jsx.snap
  tests/integerationTests/bookmarksContainer.test.jsx
  tests/unitTests/bookmarkslistActions.test.jsx
  tests/unitTests/bookmarkslistReducer.test.jsx
Labels: In progress

#37 [ft #161382361] Add tags to a single article
  src/assets/scss/style.scss
  src/containers/viewArticles/articleView.jsx
  src/containers/viewArticles/articlesView.jsx
  tests/integerationTests/ArticleView.test.jsx
Labels: Ready For Merge, Ready for review

#38 #162699940 allow users edit an article
  .codeclimate.yml
  package.json
  src/actions/articleActions.js
  src/actions/loginActions.js
  src/actions/types.js
  src/assets/css/styles.css
  src/components/AppRouter.jsx
  src/components/article/PostArticle.jsx
  src/containers/Profile/EditProfile.jsx
  src/containers/Profile/Profile.jsx
  src/containers/Profile/PublishedArticles.jsx
  src/reducers/articleReducer.js
  src/reducers/rootReducer.js
  tests/__snapshots__/profile.test.jsx.snap
  tests/integerationTests/PostArticle.test.jsx
  tests/integerationTests/PublishedArticles.test.jsx
  tests/integerationTests/__snapshots__/AppRouter.test.jsx.snap
  tests/integerationTests/__snapshots__/PostArticle.test.jsx.snap
  tests/integerationTests/__snapshots__/PublishedArticles.test.jsx.snap
  tests/loginActions.test.jsx
  tests/unitTests/ArticleAction.test.jsx
  tests/unitTests/ArticleReducer.test.jsx
  yarn.lock
Labels: Ready For Merge
